### ISSUE TITLE
Service Worker process is not working after publishing into IIS.

### ISSUE THREAD

**Issue by ankitmori14** [ASHWINI-GUPTA/ASP.NET-Core-PWA#1]
I have download your source code but after publishing into IIS i am not able to create service worker.

please suggest. thanks for help in advance.
![pwapublish](https://user-images.githubusercontent.com/28730774/41223247-eb1c4cb4-6d86-11e8-977f-dd138380eb66.JPG)

**Comment by ASHWINI-GUPTA** [comment]
I'm debugging the Application with IIS using Visual Studio, it's working fine.

![image](https://user-images.githubusercontent.com/11544667/41250781-8a126e54-6dd5-11e8-8eaf-39dd00f80d65.png)

**Comment by ankitmori14** [comment]
Try with the publish version. you will find same error that i am getting.
-I have publish into release mode and then created one website  into IIS and place that particular publish into the website folder.

**Comment by ankitmori14** [comment]
Issue is working fine for me now, issue was regarding to path of JS files which i was caching in service worker.

Thank You..
